name: Deploy Gatsby Site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: xmflsct/action-publish-gatsby@v1 # Uses this action to run further steps
        with:
          publishBranch: 'gh-pages' # Not required, default publishing branch is master
          token: ${{ secrets.NAME }} # Your personal access token of GitHub, read more below of how to obtain one and keep it safe
